openapi: 3.0.1
info:
  title: Vestis API
  description: Manage your tailoring
  contact:
    name: Vestis
    url: https://vestis.com
    email: contact@vestis.com
  version: v1
paths:
  /api/Auth/register:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
          text/json:
            schema:
              $ref: '#/components/schemas/UserModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UserModel'
      responses:
        '200':
          description: OK
  /api/Auth/login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
          text/json:
            schema:
              $ref: '#/components/schemas/UserModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UserModel'
      responses:
        '200':
          description: OK
  /api/Studios:
    get:
      tags:
        - Studios
      responses:
        '200':
          description: OK
    post:
      tags:
        - Studios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudioModel'
          text/json:
            schema:
              $ref: '#/components/schemas/StudioModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/StudioModel'
      responses:
        '200':
          description: OK
  '/api/Studios/{id}':
    get:
      tags:
        - Studios
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
  /api/Tailors:
    get:
      tags:
        - Tailors
      responses:
        '200':
          description: OK
  /api/Tailors/test:
    get:
      tags:
        - Tailors
      responses:
        '200':
          description: OK
  /api/Users:
    get:
      tags:
        - Users
      responses:
        '200':
          description: OK
components:
  schemas:
    StudioModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
          nullable: true
        deletedDate:
          type: string
          format: date-time
          nullable: true
        name:
          type: string
          nullable: true
        contactEmail:
          type: string
          nullable: true
        phoneNumber:
          type: string
          nullable: true
      additionalProperties: false
    UserModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
          nullable: true
        deletedDate:
          type: string
          format: date-time
          nullable: true
        name:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        role:
          type: string
          nullable: true
      additionalProperties: false